//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidLib.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndroidLib.Test.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;manifest xmlns:android=&quot;http://schemas.android.com/apk/res/android&quot; android:versionCode=&quot;29&quot; android:versionName=&quot;1.9&quot; android:compileSdkVersion=&quot;28&quot; android:compileSdkVersionCodename=&quot;9&quot; package=&quot;abdelrahman.wifianalyzerpro&quot; platformBuildVersionCode=&quot;29&quot; platformBuildVersionName=&quot;1.9&quot;&gt;
        ///  &lt;uses-sdk android:minSdkVersion=&quot;28&quot; android:targetSdkVersion=&quot;28&quot;/&gt;
        ///  &lt;uses-permission android:name=&quot;android.permission.ACCESS_WIFI_STATE&quot;/&gt;
        ///  &lt;uses-permission android:name=&quot;and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AndroidManifest_xml {
            get {
                return ResourceManager.GetString("AndroidManifest.xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hierarchy rotation=&quot;0&quot;&gt;
        ///  &lt;node index=&quot;123&quot; text=&quot;the text&quot; resource-id=&quot;the id&quot; class=&quot;the class&quot; package=&quot;the package&quot; content-desc=&quot;the content description&quot; checkable=&quot;true&quot; checked=&quot;true&quot; clickable=&quot;true&quot; enabled=&quot;true&quot; focusable=&quot;true&quot; focused=&quot;true&quot; scrollable=&quot;true&quot; long-clickable=&quot;true&quot; password=&quot;true&quot; selected=&quot;true&quot; bounds=&quot;[1,2][3,4]&quot;&gt;
        ///    &lt;node index=&quot;0&quot; text=&quot;&quot; resource-id=&quot;com.android.systemui:id/op_aod_bg&quot; class=&quot;android.view.View&quot; package=&quot;com.android.systemui&quot; content-desc=&quot;&quot; checkable=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HierarchyXml {
            get {
                return ResourceManager.GetString("HierarchyXml", resourceCulture);
            }
        }
    }
}
